CREATE TABLE datos_formulario
(
    ID INT(2) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    EMPRESA VARCHAR(100) NOT NULL,
    DIRECCION VARCHAR(100) NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    TELEFONO INT(9) NOT NULL,
    DNI VARCHAR(10) NOT NULL,
    CORREO VARCHAR(100) NOT NULL,
    ESPECIALIDAD VARCHAR(30) NOT NULL
);
CREATE TABLE datos_usuario
(
    ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    USUARIO VARCHAR(30),
    PASSWORD VARCHAR(30)
);